### ISSUE TITLE
[question] Speed of jb cleanupcode

### ISSUE THREAD

**Issue by adusak** [sethreno/ReGitLint#17]
Hey guys, this is not really a bug report or feature request. 
I just want to ask if you have performance issues with the jet brains tool.
I am using regitlint as a nice way to only scan the staged files. But the scan takes 2 minutes even if there is only 1 change file.
Did any of you face similar performance issues with the JetBrains tool?

**Comment by sethreno** [comment]
First off, I love the Zissou profile pic! As for speeding up jb, my understanding is that it's slow because it has to build your project first. 2 minutes seems like a long build, but of course it depends on a lot of factors. I use ReGitLint to format a couple medium size projects and it takes ~15 seconds with one modified file.

The fact that jb cleanupcode it's slow is the impetus for ReGitLint. If it was fast I'd just run it on the entire solution each time like I do with prettier.

You could try the --format-only option and --skip-tool-check but I'm guessing your gains will be minimal.

Other than that get a fast ssd if you don't have one. :)
