### ISSUE TITLE
Feature Request: .NET 8.0 Release

### ISSUE THREAD

**Issue by thejuan** [sethreno/ReGitLint#46]
Currently have to build multi-runtime images to use reglint

**Comment by bart-vmware** [comment]
I'm unable to run `dotnet regitlint` with the current GitHub Actions runner images. It fails with:
```
You must install or update .NET to run this application.

App: /home/vsts/.nuget/packages/regitlint/6.3.12/tools/net6.0/any/ReGitLint.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /opt/hostedtoolcache/dotnet/

The following frameworks were found:
  8.0.6 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64&os=ubuntu.22.04
```
The problem goes away when pre-installing .NET 6. This is because regitlint multi-targets `netcoreapp3.1;net5.0;net6.0`. I believe it should be changed to: `net8.0;net6.0`. The support for .NET 5 ended in May 2022, so I think this is old enough to be removed. Doing so reduces the NuGet file size.
